apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot-org
      defaultBucket: iot-data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    editable: false
    isDefault: true
    orgId: 1
